default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf-8
  pool: 5
  database: deadball-api
  username: postgres
development: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf-8
  pool: 5
  database: deadball-api-dev
  username: postgres
